#!/bin/bash

declare -A sync_array
declare -A ch_array

dst_chgroup="www-data"

src_root="/dfsdump/Data Archive/auto_loads"
dst_root="/jail"

#############################################
# Cluster: Archway
#############################################
cluster_src_root=$src_root"/archway"
cluster_dst_root=$dst_root"/archway/home/archway/scheduler"

#############################################
# Cluster: Archway
# Project: overdrive
# Client: ALL
#############################################

project_src_root=$cluster_src_root"/overdrive/"
sync_array[$project_src_root]=$cluster_dst_root"/overdrive"
ch_array[$project_src_root]="archway"

#############################################
# Cluster: Arthur
#############################################
cluster_src_root=$src_root"/arthur"
cluster_dst_root=$dst_root"/arthur/home/arthur/scheduler"

#############################################
# Cluster: Arthur
# Project: overdrive
# Client: ALL
#############################################

project_src_root=$cluster_src_root"/overdrive/"
sync_array[$project_src_root]=$cluster_dst_root"/overdrive"
ch_array[$project_src_root]="arthur"

#############################################
# Cluster: Avalon
#############################################
cluster_src_root=$src_root"/avalon"
cluster_dst_root=$dst_root"/avalon/home/avalon/scheduler"

#############################################
# Cluster: Avalon
# Project: overdrive
# Client: ALL
#############################################

project_src_root=$cluster_src_root"/overdrive/"
sync_array[$project_src_root]=$cluster_dst_root"/overdrive"
ch_array[$project_src_root]="avalon"


#############################################
# Cluster: Bridges
#############################################
cluster_src_root=$src_root"/bridges"
cluster_dst_root=$dst_root"/bridges/home/bridges/scheduler"

#############################################
# Cluster: Bridges
# Project: overdrive
# Client: ALL
#############################################

project_src_root=$cluster_src_root"/overdrive/"
sync_array[$project_src_root]=$cluster_dst_root"/overdrive"
ch_array[$project_src_root]="bridges"


#############################################
# Cluster: Explore
#############################################
cluster_src_root=$src_root"/explore"
cluster_dst_root=$dst_root"/explore/home/explore/scheduler"

#############################################
# Cluster: Explore
# Project: overdrive
# Client: ALL
#############################################

project_src_root=$cluster_src_root"/overdrive/"
sync_array[$project_src_root]=$cluster_dst_root"/overdrive"
ch_array[$project_src_root]="explore"


#############################################
# Cluster: KC-Towers
#############################################
cluster_src_root=$src_root"/kc-towers"
cluster_dst_root=$dst_root"/kc-towers/home/kc-towers/scheduler"

#############################################
# Cluster: KC-Towers
# Project: overdrive
# Client: ALL
#############################################

project_src_root=$cluster_src_root"/overdrive/"
sync_array[$project_src_root]=$cluster_dst_root"/overdrive"
ch_array[$project_src_root]="kc-towers"


#############################################
# Cluster: Swan
#############################################
cluster_src_root=$src_root"/swan"
cluster_dst_root=$dst_root"/swan/home/swan/scheduler"

#############################################
# Cluster: Swan
# Project: overdrive
# Client: ALL
#############################################

project_src_root=$cluster_src_root"/overdrive/"
sync_array[$project_src_root]=$cluster_dst_root"/overdrive"
ch_array[$project_src_root]="swan"


#############################################
# Cluster: KC-Towers
#############################################
cluster_src_root=$src_root"/kctowers"
cluster_dst_root=$dst_root"/kc-towers/home/kc-towers/scheduler"

#############################################
# Cluster: KC-Towers
# Project: ebook_central
#############################################

project_src_root=$cluster_src_root"/ebook_central"

#############################################
# Cluster: KC-Towers
# Project: ebook_central
# Client: MWSU
#############################################

this_src_root=$project_src_root"/mwsu/"
sync_array[$this_src_root]=$cluster_dst_root"/EBC/MWSU"
ch_array[$this_src_root]="kc-towers"

#############################################
# Cluster: KC-Towers
# Project: ebook_central
# Client: Saint Paul
#############################################

this_src_root=$project_src_root"/SPST/"
sync_array[$this_src_root]=$cluster_dst_root"/EBC/SPST"
ch_array[$this_src_root]="kc-towers"













#############################################
# Run the rsync
#############################################

for key in "${!sync_array[@]}"
do
    echo "$key"
    echo "${sync_array[$key]}"
    echo "chown: ${ch_array[$key]}"
    rsync -av -W --chown "${ch_array[$key]}":$dst_chgroup --delete "$key" "${sync_array[$key]}"
    chmod aug-x -R "${sync_array[$key]}"
    chmod aug+Xrw -R "${sync_array[$key]}"
done
